# Generated by Django 6.0.6 on 2026-07-01 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_fix_category_unique_constraint_soft_delete'),
    ]

    operations = [
        migrations.RunSQL(
            # Convert existing amounts to proper decimal format
            # PostgreSQL: use CAST to numeric. SQLite: printf already handled by default decimal storage
            "UPDATE budget_budget SET amount = CAST(amount AS numeric(10,2)) WHERE amount IS NOT NULL;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
