# Generated by Django 6.0.6 on 2026-07-01 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_fix_category_unique_constraint_soft_delete'),
    ]

    operations = [
        migrations.RunSQL(
            # Convert existing integer amounts to proper decimal format
            "UPDATE budget_budget SET amount = printf('%.2f', amount) WHERE amount IS NOT NULL;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
