# Generated by Django 6.0.6 on 2026-07-14 14:06

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def normalize_non_positive_expense_amounts(apps, schema_editor):
    Expense = apps.get_model("budget", "Expense")
    Expense.objects.filter(amount__lt=Decimal("0.01")).update(amount=Decimal("0.01"))


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_alter_expense_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            normalize_non_positive_expense_amounts,
            noop_reverse,
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', Decimal('0.01'))), name='expense_amount_gte_0_01'),
        ),
    ]
